OPENAI_API_KEY = "YOUR_KEY_WILL_BE_SET_IN_STREAMLIT"

[gcp_service_account]
type = "service_account"
project_id = "looker-bot-461918"
private_key_id = "28cc41c3d743ca7fa783d6e56b7aff515e8fad36"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDzlfm9gqg05Uuz
AjwUA8AKVlNHngwYbUeLFvN1KxEn8/fOTO9bmzB6lOqrV3rT2VpLAZ6qdtCJsfia
Xi9GskgLjrPtq62fd+8BGfd+Ua2+su6W/L9X7f0BDWWOLYMxGIWg4x/DHBf9QkVC
INLhyZbuddSju9Ix8VF4zH4xuQMyDGZNblLtpkblxqsHWbbOJN0ifMGINx8B0QWh
4heUfR+NyDEpDcxhuTzPU53EZKwTaqCMCVhx66wEUqYfO4u/g2dhPQGhol7TZhg0
EBiqqJtz1MmvgcmHqv79SeRiPFPCgEnc9kN1z2a+o7nAJ2hGzu0x3CmYtebDrkOu
in2H1NWPAgMBAAECggEAHqyrR4c1oXuincdRQ3/5ZhPa5vDrOwQ/9y8Lt5yVy384
nJ0po1KWt0kbiDo6+IStjzaEAZl2x3BHC0GDGJcI5ZOx6uMsuSFEUtIvTZQBmjs0
OoVXnz4UF1bVjCMFG2CoK0uOy2Y1SypWSG6Tv+VAAYWLIpdbb/igtuKhnadb1Khm
MK7mNB8DbP0xH4qEQ+hhIsGRvennyUP5fmHasHZY6FRosWOHI7nnWXLVYmHr1udF
qhyluUnwAn/vlVxXInr+lnpeAzAe+FUlAGJKWyuQRvghEc4heutupdmDTJb3BpAA
FYQvhDwi1yMBRJJ8Pe7OgBKHys+kkcyzQV14lQvd6QKBgQD60qkAK82vzus809cB
q8u54AARmza50i+qjTIaBK7OhT5DH+SzFPuQlgBwfCjX+JHCdVaUd6B8kAcuc8QZ
sg5TVXPfpAejdhk8tGOIKNEUMOK4SteWzY1CGiVfsASXWZpoGpfgi9gr5E3G0cwN
rkJgxqvjsbzkH1xSJph20TZNBQKBgQD4nRM3LkA1MXPK3QJ7HY0fz/lWU+8Avbxh
fZ0w04zizUBp/nuvpB7Ci/QzqlZfuhhoa+3MwhET1XK0NbCRM4OAAjPCzptBGrrX
K7JPodMz7YmgLQKvw1zQHD5iMyfVzEg5H7JSpZxPkKucZq/y0wSz6OBvLY75ucbi
LLIo4Vl8gwKBgQDR/ZRoBERMMFxZrLGRQJdrotHr65rBr+sgSt3rUohXds5NvGHo
XGTRBASSKCC5z+2YdExsOEswfhTFGz7OlHfR5PUCA34xqCow3IWH9UQ2N0dZK6+b
HbRp5yHrHp55aBcRmVIWOH5fIODM19CSk5YXF73I/4E5K9hLHuz+bOGdUQKBgQDH
Wu01qljCTs1TNrXuk1u+zr5ZgyR7q6mLY3bQ2FJ4661jUTVNOoWP6zn+0/A/ArLf
yOv+7P9UsCwyZXsYc/5Wf22SIKpOImkAcYGiaVk6opdhYbZtynJ6TquXgv3GavDf
HZOYwkP9aTyzRYSBasSyn2KYxCeKCHZ6luyl604ekQKBgHSbsCO8C2fctfNOMAv/
KQPcYgtukRBCxrz2dsW27602AYcoKUNnuwrGDtikt787YPKpYXFu04jfqmuM2PGU
Sp4jccl1FBppO4/4sqObPBUbe/Jzyl/wYQbOD19KKgSKSKVNI8rMhciILg/Lv8y6
waYUX9sH0YDMyEeYhRdL3j5/
-----END PRIVATE KEY-----"""
client_email = "sheets-bot@looker-bot-461918.iam.gserviceaccount.com"
client_id = "117355506748596904568"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-bot%40looker-bot-461918.iam.gserviceaccount.com"
<<<<<<< HEAD
universe_domain = "googleapis.com"

=======
universe_domain = "googleapis.com"
>>>>>>> 5f31303 (Initial commit with secrets.toml)
